
package repaso2venta;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafae
 */
public class index extends javax.swing.JFrame {

    private ArrayList<Producto> inventario = new ArrayList<>();
    private javax.swing.JList<String> listaProductos;
    private DefaultListModel<String> modeloLista;
    

    
    public index() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        codigoDeBarrasLabel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombreProductoLabel = new javax.swing.JTextField();
        precioLabel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        categoriaLabel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        descuentoLabel = new javax.swing.JTextField();
        guardarButton = new javax.swing.JButton();
        imprimirOrdenButton = new javax.swing.JButton();
        imprimirInversoButton = new javax.swing.JButton();
        buscarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        limpiarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Codigo de barras");

        jLabel2.setText("Nombre del producto");

        jLabel3.setText("Precio");

        jLabel4.setText("Categoria");

        categoriaLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaLabelActionPerformed(evt);
            }
        });

        jLabel5.setText("Descuento");

        guardarButton.setText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        imprimirOrdenButton.setText("Orden");
        imprimirOrdenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirOrdenButtonActionPerformed(evt);
            }
        });

        imprimirInversoButton.setText("Inverso");
        imprimirInversoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirInversoButtonActionPerformed(evt);
            }
        });

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        limpiarButton.setText("Limpiar");
        limpiarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarButtonActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo de barras", "Producto", "Precio", "Categoria", "Descuento", "Precio Final"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(descuentoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(precioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(categoriaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(codigoDeBarrasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreProductoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(682, 682, 682)
                        .addComponent(limpiarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(guardarButton)
                        .addGap(56, 56, 56)
                        .addComponent(imprimirOrdenButton)
                        .addGap(52, 52, 52)
                        .addComponent(imprimirInversoButton)
                        .addGap(75, 75, 75)
                        .addComponent(buscarButton)
                        .addGap(58, 58, 58)
                        .addComponent(eliminarButton)))
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(codigoDeBarrasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreProductoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoriaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descuentoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guardarButton)
                            .addComponent(imprimirOrdenButton)
                            .addComponent(imprimirInversoButton)
                            .addComponent(buscarButton)
                            .addComponent(eliminarButton))
                        .addGap(29, 29, 29)
                        .addComponent(limpiarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 106, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoriaLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriaLabelActionPerformed
        
    
    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        //boton para guardar los productos
        String codigo = codigoDeBarrasLabel.getText();
        String nombre = nombreProductoLabel.getText();
        double precio = Double.parseDouble(precioLabel.getText());
        String categoria = categoriaLabel.getText();
        double descuento = Double.parseDouble(descuentoLabel.getText());
        
        Producto productito = new Producto(codigo, nombre, categoria, precio, descuento);
         inventario.add(productito);
        
         JOptionPane.showMessageDialog(this, "El producto se agrego");
         

    }//GEN-LAST:event_guardarButtonActionPerformed

    private void limpiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarButtonActionPerformed
        //boton para limpiar los campos
        codigoDeBarrasLabel.setText("");
        nombreProductoLabel.setText("");
        categoriaLabel.setText("");
        precioLabel.setText("");
        descuentoLabel.setText("");

    }//GEN-LAST:event_limpiarButtonActionPerformed

    private void imprimirInversoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirInversoButtonActionPerformed
    
    DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
    modelo.setRowCount(0); //tabla limpada

    //duplicamos la lista que ya tenemos de inventario 
    List<Producto> productosInvertidos = new ArrayList<>(inventario);
    Collections.reverse(productosInvertidos); //metddo en el que ordenará los productos al reves

    //mostramos los productos desde el arreglo de manera invertida
    for (Producto producto : productosInvertidos) {
        modelo.addRow(new Object[]{
            producto.getCodigo(),
            producto.getNombre(),
            producto.getCategoria(),
            producto.getPrecio(),
            producto.getDescuento(),
            producto.getPrecioFinal()
        });
    }


    }//GEN-LAST:event_imprimirInversoButtonActionPerformed

    private void imprimirOrdenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirOrdenButtonActionPerformed
       //boton para imprimir en orden de productos 
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        modelo.setRowCount(0); //tabla limpada
        
        for (Producto producto : inventario) {
        modelo.addRow(new Object[]{
            producto.getCodigo(),
            producto.getNombre(),
            producto.getCategoria(),
            producto.getPrecio(),
            producto.getDescuento(),
            producto.getPrecioFinal()
        });
        }
    }//GEN-LAST:event_imprimirOrdenButtonActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        // boton buscar
        String codigoBuscado = codigoDeBarrasLabel.getText().trim(); //el codigo buscado es igual al texto que salga del label

    if (codigoBuscado.isEmpty()) { //si esta vacio muestra un pane de alerta 
        JOptionPane.showMessageDialog(this, "Ingresa un codigo valido");
        return;
    }

    DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
    modelo.setRowCount(0); //tabla limpiada

    boolean encontrado = false; //falso porque aun no se encuentra nada

    for (Producto producto : inventario) {
        if (producto.getCodigo().equalsIgnoreCase(codigoBuscado)) { //condicion de busqueda, si el producto del label es igual a codgioBUscado
            modelo.addRow(new Object[]{
                producto.getCodigo(),
                producto.getNombre(),
                producto.getCategoria(),
                producto.getPrecio(),
                producto.getDescuento(),
                producto.getPrecioFinal()
            });
            encontrado = true;
            break; 
        }
    }

    if (!encontrado) {
        JOptionPane.showMessageDialog(this, "No se encontro.");
    }

    }//GEN-LAST:event_buscarButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        //boton eliminar
           String codigoBuscado = codigoDeBarrasLabel.getText().trim();

    if (codigoBuscado.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Codigo de barras a eliminar.");
        return;
    }

    Producto productoAEliminar = null;

    for (Producto p : inventario) {
        if (p.getCodigo().equalsIgnoreCase(codigoBuscado)) {
            productoAEliminar = p;
            break;
        }
    }

    if (productoAEliminar == null) {
        JOptionPane.showMessageDialog(this, "No existe el prodcuto.");
        return;
    }

    int confirmacion = JOptionPane.showConfirmDialog(this, "Quiere eliminar el producto: " + productoAEliminar.getNombre() + "?", "Confirmar eliminacion",JOptionPane.YES_NO_OPTION);

    if (confirmacion == JOptionPane.YES_OPTION) {inventario.remove(productoAEliminar); //borra del inventario

        // tabla cambiada
        imprimirOrdenButtonActionPerformed(null); 
        JOptionPane.showMessageDialog(this, "El producto se eliminó de manera correcta.");
    }

    }//GEN-LAST:event_eliminarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButton;
    private javax.swing.JTextField categoriaLabel;
    private javax.swing.JTextField codigoDeBarrasLabel;
    private javax.swing.JTextField descuentoLabel;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JButton guardarButton;
    private javax.swing.JButton imprimirInversoButton;
    private javax.swing.JButton imprimirOrdenButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiarButton;
    private javax.swing.JTextField nombreProductoLabel;
    private javax.swing.JTextField precioLabel;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
